const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Plugins.Date,
		C3.Behaviors.Tween,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Fade,
		C3.Plugins.Cryptography,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Clipboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetCollisionFilter,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Physics.Acts.ApplyTorqueToAngle,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Cnds.OnInstanceSignal,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.InstanceSignal,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.ChangeTags,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetMonth,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.DrawingCanvas.Cnds.OnCreated,
		C3.Plugins.DrawingCanvas.Acts.SetPosToObject,
		C3.Plugins.DrawingCanvas.Acts.MoveToBottom,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.DrawingCanvas.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.DrawingCanvas.Exps.Angle,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.DrawingCanvas.Cnds.IsOnScreen,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Date.Exps.ToTotalSeconds,
		C3.Plugins.Date.Exps.Difference,
		C3.Plugins.Date.Exps.Get,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Exps.chooseindex,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Exps.IID,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.Browser.Exps.Platform,
		C3.Plugins.Browser.Exps.URL,
		C3.Plugins.BinaryData.Acts.SetFromText,
		C3.Plugins.Cryptography.Acts.EncryptBinary,
		C3.Plugins.Cryptography.Cnds.OnEncryptionFinished,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Date.Exps.ToLocaleDateString,
		C3.Plugins.System.Exps.time,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Clipboard.Acts.RequestPasteText,
		C3.Plugins.Clipboard.Cnds.OnPasteText,
		C3.Plugins.Clipboard.Exps.PastedText,
		C3.Plugins.BinaryData.Acts.SetFromBase64,
		C3.Plugins.Cryptography.Acts.DecryptBinary,
		C3.Plugins.Cryptography.Cnds.OnDecryptionFinished,
		C3.Plugins.BinaryData.Exps.GetAllText,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Text.Exps.TextHeight,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.Text.Exps.PickedCount,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.JavaScriptInEvents._global_Event20_Act2,
		C3.JavaScriptInEvents._global_Event21_Act2,
		C3.Plugins.Text.Acts.SetVAlign,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.System.Exps.regexmatchat,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Acts.StopLoop,
		C3.JavaScriptInEvents._global_Event54_Act2,
		C3.JavaScriptInEvents._global_Event55_Act2,
		C3.JavaScriptInEvents._global_Event64_Act2,
		C3.JavaScriptInEvents._global_Event65_Act2,
		C3.JavaScriptInEvents._global_Event66_Act2,
		C3.JavaScriptInEvents._global_Event67_Act2
	];
};
self.C3_JsPropNameTable = [
	{isDragging: 0},
	{drag: 0},
	{g: 0},
	{extraG: 0},
	{cuttable: 0},
	{origW: 0},
	{origH: 0},
	{tsy: 0},
	{colltags: 0},
	{watchSelfCollision: 0},
	{colltagsExtra: 0},
	{tarjeta: 0},
	{ganchoBack: 0},
	{n: 0},
	{spawn: 0},
	{Physics: 0},
	{gancho: 0},
	{brillo: 0},
	{numero: 0},
	{physicsSolidTarjeta: 0},
	{Touch: 0},
	{Anchor: 0},
	{physicsSolid: 0},
	{joint: 0},
	{Browser: 0},
	{Mes: 0},
	{Calendario: 0},
	{sf_Numeros: 0},
	{Date: 0},
	{Tween: 0},
	{PasaPagina: 0},
	{Bullet: 0},
	{DrawingCanvas: 0},
	{Mask: 0},
	{SelectDay: 0},
	{Particles: 0},
	{switchScreen: 0},
	{sp_pop: 0},
	{targetText: 0},
	{totalTextHeight: 0},
	{Timer: 0},
	{Text: 0},
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Fade: 0},
	{s_Fade: 0},
	{Cryptography: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{Clipboard: 0},
	{LocalStorage: 0},
	{Text2: 0},
	{"9patch": 0},
	{physics: 0},
	{orig: 0},
	{otherTarjetas: 0},
	{AnimatedTexts: 0},
	{switchCount: 0},
	{cancel: 0},
	{f: 0},
	{dragX: 0},
	{dragY: 0},
	{maxVelPhysics: 0},
	{dragMult: 0},
	{tlf: 0},
	{tt: 0},
	{lado: 0},
	{mes: 0},
	{dia: 0},
	{M: 0},
	{D: 0},
	{cancelAuto: 0},
	{slideshow: 0},
	{password: 0},
	{S: 0},
	{WebAppURL: 0},
	{text: 0},
	{typewriteTime: 0},
	{regexMatchBeforeBBcode: 0},
	{regexMatchBBcodeTag: 0},
	{regexMatchBBcodeValues: 0},
	{regexMatchBBcodeText: 0},
	{regexMatchBBcode: 0},
	{animateTags: 0},
	{finalText: 0},
	{typewriterStyle: 0},
	{typewriteProgress: 0},
	{typeWritterOffsetEffect: 0},
	{hidden: 0},
	{textTarget: 0},
	{tag: 0},
	{values: 0},
	{valueMult: 0},
	{speedMult: 0},
	{freqMult: 0},
	{value: 0},
	{skip: 0},
	{char: 0},
	{faceSize: 0},
	{offsetY: 0},
	{index: 0},
	{String: 0},
	{part: 0},
	{rep: 0}
];

self.InstanceType = {
	tarjeta: class extends self.ISpriteInstance {},
	ganchoBack: class extends self.ISpriteInstance {},
	gancho: class extends self.ISpriteInstance {},
	brillo: class extends self.ISpriteInstance {},
	numero: class extends self.ISpriteInstance {},
	physicsSolidTarjeta: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	physicsSolid: class extends self.ISpriteInstance {},
	joint: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Mes: class extends self.ISpriteInstance {},
	Calendario: class extends self.ISpriteInstance {},
	sf_Numeros: class extends self.ISpriteFontInstance {},
	Date: class extends self.IInstance {},
	PasaPagina: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Mask: class extends self.ISpriteInstance {},
	SelectDay: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	switchScreen: class extends self.ISpriteInstance {},
	sp_pop: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	s_Fade: class extends self.ISpriteInstance {},
	Cryptography: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Clipboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	_9patch: class extends self.I9PatchInstance {},
	physics: class extends self.ISpriteInstance {},
	orig: class extends self.ISpriteInstance {},
	otherTarjetas: class extends self.ISpriteInstance {},
	AnimatedTexts: class extends self.ITextInstance {}
}